version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - TZ=UTC
    networks:
      - airrelay-network

  mqtt:
    image: emqx/emqx:5.4.0
    restart: unless-stopped
    ports:
      - "8883:8883"
      - "9001:9001"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - ./certs/server.key:/etc/emqx/certs/server.key:ro
      - ./certs/server.crt:/etc/emqx/certs/server.crt:ro
    environment:
      - EMQX_DASHBOARD__DEFAULT_USERNAME=${EMQX_DASHBOARD_USER}
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=${EMQX_DASHBOARD_PASSWORD}
      - EMQX_LISTENER__SSL__EXTERNAL=8883
      - EMQX_LISTENER__SSL__EXTERNAL__KEYFILE=/etc/emqx/certs/server.key
      - EMQX_LISTENER__SSL__EXTERNAL__CERTFILE=/etc/emqx/certs/server.crt
      - EMQX_LISTENER__SSL__EXTERNAL__VERIFY=verify_none
    networks:
      - airrelay-network

networks:
  airrelay-network:
    driver: bridge

volumes:
  emqx-data:
  emqx-log: 